### ISSUE TITLE
`yarn dev` fail

### ISSUE THREAD

**Issue by otmjka** [strues/react-universal-boiler#21]
Hi @strues can you help me?
 
I've cloned the repo. 
`yarn install`
`cp .env.example .env`
`yarn dev`
and got error: 

```
🚀  Server running on port: 3000
webpack building...
✔ CLIENT Done!
webpack built f90881dd0b43fdcbcd91 in 3887ms
✔ SERVER Done!

/Users/otmjka/projects/psyprofile/node_modules/memory-fs/lib/MemoryFileSystem.js:112
			throw new MemoryFileSystemError(errors.code.EISDIR, _path);
			^
Error
    at MemoryFileSystem.readFileSync (/Users/otmjka/projects/psyprofile/node_modules/memory-fs/lib/MemoryFileSystem.js:112:10)
    at MultiCompiler.multiCompiler.plugin.multiStats (/Users/otmjka/projects/psyprofile/node_modules/webpack-hot-server-middleware/src/index.js:119:33)
    at MultiCompiler.applyPlugins (/Users/otmjka/projects/psyprofile/node_modules/tapable/lib/Tapable.js:61:14)
    at Compiler.compiler.plugin.stats (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/MultiCompiler.js:33:11)
    at Compiler.applyPlugins (/Users/otmjka/projects/psyprofile/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:368:12)
    at Compiler.applyPluginsAsyncSeries1 (/Users/otmjka/projects/psyprofile/node_modules/tapable/lib/Tapable.js:211:46)
    at Compiler.afterEmit (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/otmjka/projects/psyprofile/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/otmjka/projects/psyprofile/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/otmjka/projects/psyprofile/node_modules/async/dist/async.js:998:13)
    at /Users/otmjka/projects/psyprofile/node_modules/async/dist/async.js:906:16
[nodemon] app crashed - waiting for file changes before starting...
```

Start debugging and found the error raised at 
`/server/middleware/hot.js`

```
app.use(
  webpackHotServerMiddleware(multiCompiler, {
    serverRendererOptions: { outputPath },
  }),
);
```

And mb it is the same problem as described [here](https://github.com/60frames/webpack-hot-server-middleware/issues/12)

Have you the same problem?

**Comment by strues** [comment]
I hadn't experienced the issue @otmjka until I went to check. Now it's happening. I'll look into it.

**Comment by strues** [comment]
Resolved now. The chunkName: 'server' added https://github.com/strues/react-universal-boiler/blob/master/server/middleware/hot.js#L47 solves the problem.
