### ISSUE TITLE
Deployment help (Heroku)

### ISSUE THREAD

**Issue by harry008** [strues/react-universal-boiler#9]
Hi, I've deployed my repo on Heroku. For heroku build I had to move some dev deps to main deps.
I think this error related with webpack-isomorphic-tools ( for port maybe).
Here are the logs for my app:

```bash
2016-10-12T08:56:22.547151+00:00 app[web.1]: npm ERR! not with npm itself.
2016-10-12T08:56:22.547322+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-10-12T08:56:22.547473+00:00 app[web.1]: npm ERR!     npm run start:prod
2016-10-12T08:56:22.547624+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-10-12T08:56:22.551856+00:00 app[web.1]: npm ERR!     npm bugs manavjyot-charity-app
2016-10-12T08:56:22.552011+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-10-12T08:56:22.552145+00:00 app[web.1]: npm ERR!     npm owner ls manavjyot-charity-app
2016-10-12T08:56:22.552291+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-10-12T08:56:22.622169+00:00 app[web.1]:
2016-10-12T08:56:22.622395+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-10-12T08:56:22.622501+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-10-12T08:56:22.727290+00:00 heroku[web.1]: Process exited with status 1
2016-10-12T08:56:22.738402+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-12T14:40:24.804716+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-12T14:40:30.187206+00:00 heroku[web.1]: Starting process with command `npm start`
2016-10-12T14:40:33.561868+00:00 app[web.1]:
2016-10-12T14:40:33.561882+00:00 app[web.1]: > manavjyot-charity-app@0.1.1 start /app
2016-10-12T14:40:33.561883+00:00 app[web.1]: > npm run start:prod
2016-10-12T14:40:33.561883+00:00 app[web.1]:
2016-10-12T14:40:35.099249+00:00 app[web.1]:
2016-10-12T14:40:35.099259+00:00 app[web.1]: > manavjyot-charity-app@0.1.1 start:prod /app
2016-10-12T14:40:35.099260+00:00 app[web.1]: > better-npm-run start:prod
2016-10-12T14:40:35.099261+00:00 app[web.1]:
2016-10-12T14:40:35.288827+00:00 app[web.1]: running better-npm-run in /app
2016-10-12T14:40:35.385011+00:00 app[web.1]: Executing script: start:prod
2016-10-12T14:40:35.386687+00:00 app[web.1]: to be executed: node ./bin/run.js
2016-10-12T14:40:35.385020+00:00 app[web.1]:
2016-10-12T14:40:38.422148+00:00 app[web.1]: Wed, 12 Oct 2016 14:40:38 GMT express-session deprecated req.secret; provide secret option at static/server.js:728:38
2016-10-12T14:40:38.491564+00:00 app[web.1]: RangeError: "port" argument must be >= 0 and < 65536
2016-10-12T14:40:38.491568+00:00 app[web.1]:     at assertPort (internal/net.js:17:11)
2016-10-12T14:40:38.491569+00:00 app[web.1]:     at Server.listen (net.js:1383:5)
2016-10-12T14:40:38.491570+00:00 app[web.1]:     at Object.<anonymous> (/app/static/webpack:/src/server.js:268:8)
2016-10-12T14:40:38.491571+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/static/server.js:894:30)
2016-10-12T14:40:38.491571+00:00 app[web.1]:     at __webpack_require__ (/app/static/webpack:/webpack/bootstrap aef6249a0924d9e9ac1b:19:1)
2016-10-12T14:40:38.491572+00:00 app[web.1]:     at Object.<anonymous> (/app/static/server.js:4613:18)
2016-10-12T14:40:38.491573+00:00 app[web.1]:     at __webpack_require__ (/app/static/webpack:/webpack/bootstrap aef6249a0924d9e9ac1b:19:1)
2016-10-12T14:40:38.491574+00:00 app[web.1]:     at /app/static/webpack:/webpack/bootstrap aef6249a0924d9e9ac1b:63:1
2016-10-12T14:40:38.491574+00:00 app[web.1]:     at Object.<anonymous> (/app/static/server.js:68:10)
2016-10-12T14:40:38.491575+00:00 app[web.1]:     at Module._compile (module.js:556:32)
2016-10-12T14:40:38.491579+00:00 app[web.1]:     at Module.require._compile (/app/node_modules/webpack-isomorphic-tools/source/index.js:507:28)
2016-10-12T14:40:38.491579+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:565:10)
2016-10-12T14:40:38.491580+00:00 app[web.1]:     at Module.load (module.js:473:32)
2016-10-12T14:40:38.491581+00:00 app[web.1]:     at tryModuleLoad (module.js:432:12)
2016-10-12T14:40:38.491581+00:00 app[web.1]:     at Function.Module._load (module.js:424:3)
2016-10-12T14:40:38.491582+00:00 app[web.1]:     at Module.require (module.js:483:17)
2016-10-12T14:40:38.491582+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-10-12T14:40:38.491583+00:00 app[web.1]:     at global.webpackIsomorphicTools.WebpackIsomorphicTools.server (/app/bin/run.js:19:5)
2016-10-12T14:40:38.491584+00:00 app[web.1]:     at check (/app/node_modules/webpack-isomorphic-tools/source/index.js:787:13)
2016-10-12T14:40:38.491584+00:00 app[web.1]:     at wait_for (/app/node_modules/webpack-isomorphic-tools/source/index.js:803:4)
2016-10-12T14:40:38.491585+00:00 app[web.1]:     at Immediate.<anonymous> (/app/node_modules/webpack-isomorphic-tools/source/index.js:841:22)
2016-10-12T14:40:38.491586+00:00 app[web.1]:     at runCallback (timers.js:574:20)
2016-10-12T14:40:38.491586+00:00 app[web.1]:     at tryOnImmediate (timers.js:554:5)
2016-10-12T14:40:38.491587+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by strues** [comment]
Looks like the port isnt being passed in.

https://github.com/strues/react-universal-boiler/blob/master/src/server.js#L95

try replacing it with this:
`server.listen(process.env.SSR_PORT || config.SSR_PORT, (err) => {`
